[package]
name = "arnak"
version = "0.1.0"
authors = ["Matthew Thompson <mat@matthewjthompson.co.uk>"]
description = "A Rust library for the BoardGameGeek XML API"
edition = "2021"
license = "MIT"
repository = "https://github.com/MatthewThompson/arnak"

[dependencies]
